CREATE TABLE softwareengineer_registration (
    ApplicantID INT(11) NOT NULL AUTO_INCREMENT, -- UNIQUE IDENTIFIER FOR EACH APPLICANTS
    FirstName VARCHAR(100) NOT NULL, -- FIRST NAME OF THE APPLICANT
    LastName VARCHAR(100) NOT NULL, -- LAST NAME OF THE APPLICANT
    Gender ENUM('Male', 'Female',) NOT NULL, -- GENDER OF THE APPLICANT
    HomeAddress VARCHAR(255) NOT NULL, -- ADDRESS OF THE APPLICANT
    Email VARCHAR(100) NOT NULL, -- EMAIL OF THE APPLICANT
    CollegeDegree VARCHAR(100) NOT NULL, -- COLLEGE DEGREE OF THE APPLICANT
    Skills TEXT NOT NULL, -- LIST OF SKILLS OR PROGRAMMING LANGUAGE THAT THE APPLICANT IS EQUIPED WITH
    Experience TEXT NOT NULL,-- YEARS OF EXPERIENCE OF THE APPLICANT
    DateAdded TIMESTAMP DEFAULT CURRENT_TIMESTAMP, -- DATE AND TIME THE RECORD WAS CREATED
    PRIMARY KEY ('ApplicantID')
);

